
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "thirumalesh_kummari",
  "password": "thiru@333",
  "name": "Thirumalesh Kummari",
  "gender": "male"
}
###


POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"thirumalesh_kummari",
  "password":"thiru@333"
}
###

GET http://localhost:3000/sample
###

POST http://localhost:3000/transcations
Content-Type: application/json

{
   "type": "income",
  "category": "salary",
  "amount": 5000,
  "date": "2024-10-22",
  "description": "October salary"
    
}
###

GET http://localhost:3000/transcations
###

GET http://localhost:3000/transcations/1/
###

PUT http://localhost:3000/transcations/1/
Content-Type: application/json

{
  "type": "expense",
  "category": "groceries",
  "amount": 150,
  "date": "2024-10-23",
  "description": "Weekly groceries"
}
###

DELETE http://localhost:3000/transcations/1/
###

GET http://localhost:3000/summary
Content-Type: application/json


{
  "income": 5000,
  "expense": 150,
  "balance": 4850
}

###